import pkg from 'pg';
const { Client } = pkg;
const c = new Client({ connectionString: process.env.DATABASE_URL });
await c.connect();
await c.query('DROP TABLE IF EXISTS "leave" CASCADE;');
console.log('dropped leave');
await c.query('DROP TABLE IF EXISTS "postings" CASCADE;');
await c.query('DROP TABLE IF EXISTS "assessments" CASCADE;');
console.log('dropped others');
process.exit(0);
